# Generated by Django 2.2 on 2019-09-03 20:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxScore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('game', models.IntegerField()),
                ('away', django.contrib.postgres.fields.jsonb.JSONField()),
                ('home', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('away_team', models.IntegerField()),
                ('home_team', models.IntegerField()),
                ('box_score', models.IntegerField()),
            ],
        ),
    ]
