# Generated by Django 2.2 on 2019-09-04 22:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190904_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxscore',
            name='starters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
