# Generated by Django 2.2 on 2019-09-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_boxscore_starters'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team_name',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_name',
            field=models.TextField(default='h'),
        ),
    ]
