from django.db import models
from django.contrib.postgres.fields import ArrayField, JSONField

# Create your models here.
class Game(models.Model):
  id = models.IntegerField(primary_key=True)
  date = models.DateField(auto_now=False, auto_now_add=False)
  away_team = models.IntegerField()
  away_team_name = models.TextField(default="a")
  home_team = models.IntegerField()
  home_team_name = models.TextField(default="h")
  box_score = models.IntegerField()

class BoxScore(models.Model):
  id = models.IntegerField(primary_key=True)
  game = models.IntegerField()
  score_away = models.IntegerField(default=0)
  score_home = models.IntegerField(default=0)
  starters = JSONField(default=list, blank=True, null=True)
  away = JSONField(default=list, blank=True, null=True)
  home = JSONField(default=list, blank=True, null=True)
  a_q1 = JSONField(default=list, blank=True, null=True)
  a_q2 = JSONField(default=list, blank=True, null=True)
  a_q3 = JSONField(default=list, blank=True, null=True)
  a_q4 = JSONField(default=list, blank=True, null=True)
  h_q1 = JSONField(default=list, blank=True, null=True)
  h_q2 = JSONField(default=list, blank=True, null=True)
  h_q3 = JSONField(default=list, blank=True, null=True)
  h_q4 = JSONField(default=list, blank=True, null=True)
  a_3 = JSONField(default=list, blank=True, null=True)
  a_6 = JSONField(default=list, blank=True, null=True)
  a_9 = JSONField(default=list, blank=True, null=True)
  a_12 = JSONField(default=list, blank=True, null=True)
  a_15 = JSONField(default=list, blank=True, null=True)
  a_18 = JSONField(default=list, blank=True, null=True)
  a_21 = JSONField(default=list, blank=True, null=True)
  a_24 = JSONField(default=list, blank=True, null=True)
  a_27 = JSONField(default=list, blank=True, null=True)
  a_30 = JSONField(default=list, blank=True, null=True)
  a_33 = JSONField(default=list, blank=True, null=True)
  a_36 = JSONField(default=list, blank=True, null=True)
  a_39 = JSONField(default=list, blank=True, null=True)
  a_42 = JSONField(default=list, blank=True, null=True)
  a_45 = JSONField(default=list, blank=True, null=True)
  a_48 = JSONField(default=list, blank=True, null=True)
  h_3 = JSONField(default=list, blank=True, null=True)
  h_6 = JSONField(default=list, blank=True, null=True)
  h_9 = JSONField(default=list, blank=True, null=True)
  h_12 = JSONField(default=list, blank=True, null=True)
  h_15 = JSONField(default=list, blank=True, null=True)
  h_18 = JSONField(default=list, blank=True, null=True)
  h_21 = JSONField(default=list, blank=True, null=True)
  h_24 = JSONField(default=list, blank=True, null=True)
  h_27 = JSONField(default=list, blank=True, null=True)
  h_30 = JSONField(default=list, blank=True, null=True)
  h_33 = JSONField(default=list, blank=True, null=True)
  h_36 = JSONField(default=list, blank=True, null=True)
  h_39 = JSONField(default=list, blank=True, null=True)
  h_42 = JSONField(default=list, blank=True, null=True)
  h_45 = JSONField(default=list, blank=True, null=True)
  h_48 = JSONField(default=list, blank=True, null=True)

